inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.1
  SuggestExtensions: false

RSpec/EmptyLineAfterHook:
  Enabled: false

Style/HashConversion:
  Exclude:
    - spec/**/*_spec.rb
